config/routes.rb
Rails.application.routes.draw do
  resources :playlists, except: [:show]
  post 'playlists/:id' => 'playlists#change_active_state'

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  sync :all
  before_save :falsify_all_others
  after_create :falsify_all_others

  def falsify_all_others
    # REFACTORING NEEDED
    Playlist.where('id != ?', id).update_all("active = 'false'") if active == true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [
    :show, :edit, :update, :destroy, :change_active_state
  ]

  # GET /playlists
  # GET /playlists.json
  def index
    @playlists = Playlist.order(:created_at)
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit
  end

  def change_active_state
    if @playlist.update(playlist_active_params)
      sync_update @playlist
      redirect_to playlists_path, notice: 'Playlist was successfully updated.'
    else
      redirect_to playlists_path
    end
  end

  # POST /playlists
  # POST /playlists.json
  def create
    @playlist = Playlist.new(playlist_params)

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to playlists_path, notice: 'Playlist was successfully created.' }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists/1
  # PATCH/PUT /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        sync_update @playlist
        format.html { redirect_to playlists_path, notice: 'Playlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to playlists_url, notice: 'Playlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_playlist
    @playlist = Playlist.find(params[:id])
  end

  # Never trust parameters from the scary internet, only
  # allow the white list through.
  def playlist_params
    params.require(:playlist).permit(:name, :url, :active)
  end

  def playlist_active_params
    params.permit(:active)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsRealTimePlaylists</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag Sync.adapter_javascript_url %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/playlists/_form.html.slim
= form_for @playlist do |f|
  - if @playlist.errors.any?
    #error_explanation
      h2 = "#{pluralize(@playlist.errors.count, "error")} prohibited this playlist from being saved:"
      ul
        - @playlist.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :url
    = f.text_field :url
  .field
    = f.label :active
    = f.check_box :active
  .actions = f.submit 'Save'

app/views/playlists/edit.html.slim
h1 Editing playlist

== render 'form'

= link_to 'Show', @playlist
'|
= link_to 'Back', playlists_path

app/views/playlists/index.html.slim
h1 Listing playlists
p#notice = notice

table(width='65%')
  thead
    tr
      th(width='20%') Name
      th(width='30%') Url
      th(width='15%') Active
      th(width='15%')
      th(width='10%')
      th(width='10%')

  tbody
    - @playlists.each do |playlist|
      = sync partial: 'playlist_row', resource: playlist

br
= link_to 'New Playlist', new_playlist_path

app/views/playlists/new.html.slim
h1 New playlist

== render 'form'

= link_to 'Back', playlists_path

app/views/playlists/show.html.slim
p#notice = notice

p
  strong Name:
  = @playlist.name
p
  strong Url:
  = @playlist.url
p
  strong Active:
  = @playlist.active

= link_to 'Edit', edit_playlist_path(@playlist)
'|
= link_to 'Back', playlists_path

app/views/sync/playlists/_playlist_row.html.slim
tr
  td = playlist.name
  td = playlist.url
  td class=((playlist.active ? 'active' : 'inactive'))
    = playlist.active
  - if playlist.active?
    td = link_to 'Set inactive', playlist_path(playlist, {active: false}), method: :change_active_state
  - else
    td = link_to 'Set active', playlist_path(playlist, {active: true}), method: :change_active_state
  td = link_to 'Edit', edit_playlist_path(playlist)
  td = link_to 'Destroy', playlist, data: {:confirm => 'Are you sure?'}, :method => :delete